apiVersion: v1
kind: Service
metadata:
  name: enterprise-system-20260519-210256-b5sjufpy6dz7-service
spec:
  selector:
    app: enterprise-system-20260519-210256-b5sjufpy6dz7
  ports:
  - port: 80
    targetPort: 8000
  type: ClusterIP
